
-- Layout icons
theme.layout_tile        = theme.dir .. "/layouts/tile.png"
theme.layout_tileleft    = theme.dir .. "/layouts/tileleft.png"
theme.layout_tilebottom  = theme.dir .. "/layouts/tilebottom.png"
theme.layout_tiletop     = theme.dir .. "/layouts/tiletop.png"
theme.layout_fairv       = theme.dir .. "/layouts/fairv.png"
theme.layout_fairh       = theme.dir .. "/layouts/fairh.png"
theme.layout_spiral      = theme.dir .. "/layouts/spiral.png"
theme.layout_dwindle     = theme.dir .. "/layouts/dwindle.png"
theme.layout_max         = theme.dir .. "/layouts/max.png"
theme.layout_fullscreen  = theme.dir .. "/layouts/fullscreen.png"
theme.layout_magnifier   = theme.dir .. "/layouts/magnifier.png"
theme.layout_floating    = theme.dir .. "/layouts/floating.png"
theme.layout_cornernw    = theme.dir .. "/layouts/cornernw.png"
theme.layout_cornerne    = theme.dir .. "/layouts/cornerne.png"
theme.layout_cornersw    = theme.dir .. "/layouts/cornersw.png"
theme.layout_cornerse    = theme.dir .. "/layouts/cornerse.png"
theme.layout_cascade     = theme.dir .. "/layouts/cascade.png"
theme.layout_cascadetile = theme.dir .. "/layouts/cascadetile.png"
theme.layout_centerfair  = theme.dir .. "/layouts/centerfair.png"
theme.layout_centerwork  = theme.dir .. "/layouts/centerwork.png"
theme.layout_centerworkh = theme.dir .. "/layouts/centerworkh.png"
theme.layout_termfair    = theme.dir .. "/layouts/termfair.png"
theme.layout_treetile    = theme.dir .. "/layouts/treetile.png"
theme.layout_machi       = theme.dir .. "/layouts/machi.png"
