[general]
live_config_reload = true
import = [
    "~/.cache/wal/colors-alacritty.toml"
]


[window]
#decorations = "none"
dynamic_title = true
opacity = 0.8


[font]
size = 10.5

[font.normal]
family = "Hack"

[font.bold]
family = "Hack"
style = "Bold"

[font.italic]
family = "Hack"
style = "Italic"
